config/routes.rb
Rails.application.routes.draw do
  resources :mensagems, only: :index

 end

app/models/mensagem.rb
class Mensagem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mensagems_controller.rb
class MensagemsController < ApplicationController
  before_action :set_mensagem, only: [:show, :edit, :update, :destroy]

  # GET /mensagems
  # GET /mensagems.json
  def index
    @mensagems = Mensagem.all

    @ofendi = Mensagem.where(tipo: "Ofendi")
    @dei_bolo = Mensagem.where(tipo: "Dei Bolo")
    @foi_sem_querer = Mensagem.where(tipo: "Foi Sem Querer")
  end

  # GET /mensagems/1
  # GET /mensagems/1.json
  def show
  end

  # GET /mensagems/new
  def new
    @mensagem = Mensagem.new
  end

  # GET /mensagems/1/edit
  def edit
  end

  # POST /mensagems
  # POST /mensagems.json
  def create
    @mensagem = Mensagem.new(mensagem_params)

    respond_to do |format|
      if @mensagem.save
        format.html { redirect_to @mensagem, notice: 'Mensagem was successfully created.' }
        format.json { render :show, status: :created, location: @mensagem }
      else
        format.html { render :new }
        format.json { render json: @mensagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mensagems/1
  # PATCH/PUT /mensagems/1.json
  def update
    respond_to do |format|
      if @mensagem.update(mensagem_params)
        format.html { redirect_to @mensagem, notice: 'Mensagem was successfully updated.' }
        format.json { render :show, status: :ok, location: @mensagem }
      else
        format.html { render :edit }
        format.json { render json: @mensagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mensagems/1
  # DELETE /mensagems/1.json
  def destroy
    @mensagem.destroy
    respond_to do |format|
      format.html { redirect_to mensagems_url, notice: 'Mensagem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mensagem
      @mensagem = Mensagem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mensagem_params
      params.require(:mensagem).permit(:tipo, :conteudo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mensagems_helper.rb
module MensagemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>iSorry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/mensagems/_form.html.erb
<%= form_for(@mensagem) do |f| %>
  <% if @mensagem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mensagem.errors.count, "error") %> prohibited this mensagem from being saved:</h2>

      <ul>
      <% @mensagem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :conteudo %><br>
    <%= f.text_area :conteudo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mensagems/edit.html.erb
<h1>Editing mensagem</h1>

<%= render 'form' %>

<%= link_to 'Show', @mensagem %> |
<%= link_to 'Back', mensagems_path %>

app/views/mensagems/index.html.erb
<h1>iSorry</h1>
<h3>Ofendi</h3>
<div class='tipo row'>
  <% @ofendi.each do |mensagem| %>
   <div class='col-lg-4'>
     <div class='mensagem'><%= mensagem.conteudo %></div>
   </div> 
  <% end %>
</div>

<h3>Dei Bolo</h3>
<div class='tipo row'>
  <% @dei_bolo.each do |mensagem| %>
   <div class='col-lg-4'>
     <div class='mensagem'><%= mensagem.conteudo %></div>
   </div> 
  <% end %>
</div>  

<h3>Foi Sem Querer</h3>
<div class='tipo row'>
  <% @foi_sem_querer.each do |mensagem| %>
   <div class='col-lg-4'>
     <div class='mensagem'><%= mensagem.conteudo %></div>
   </div> 
  <% end %>
</div>     

<br>

app/views/mensagems/new.html.erb
<h1>New mensagem</h1>

<%= render 'form' %>

<%= link_to 'Back', mensagems_path %>

app/views/mensagems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @mensagem.tipo %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @mensagem.conteudo %>
</p>

<%= link_to 'Edit', edit_mensagem_path(@mensagem) %> |
<%= link_to 'Back', mensagems_path %>